#### general settings
name: UNet_attention_u64_wDiff
use_tb_logger: true
model: video_attntion
distortion: sr
scale: 1
gpu_ids: [6]

#### datasets
datasets:
  train:
    name: Vimeo90K_LQ
    mode: Vimeo90K_LQ
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /home/web_server/zhouhuanxiang/disk/vimeo/vimeo_septuplet/sequences
    dataroot_LQ: /home/web_server/zhouhuanxiang/disk/vimeo/vimeo_septuplet/sequences_blocky37
    dataroot_LLQ: /home/web_server/zhouhuanxiang/disk/vimeo/vimeo_septuplet/sequences_blocky32
    dataroot_LHQ: /home/web_server/zhouhuanxiang/disk/vimeo/vimeo_septuplet/sequences_blocky42
    cache_keys: ~

    N_frames: 7
    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 32
    GT_size: 256
    LQ_size: 256
    use_flip: true
    use_rot: true
    color: RGB

    patch_size: 32
    patch_repeat: 5
    use_diff: true

#### network structures
network_G:
  which_model_G: Unet
  nf: 64
  HR_in: true
  G_type: unet_256
  norm: instance
  dropout: false
  init_type: normal
  init_gain: 0.02


#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 120000
  warmup_iter: -1  # -1: no warm up
  T_period: [30000, 30000, 30000, 30000]
  restarts: [30000, 60000, 90000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: bce
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3

# python ~/zhouhuanxiang/mmsr/codes/train.py -opt ~/zhouhuanxiang/mmsr/codes/options/train/train_UNet_attention_u256_wDiff.yml
